class FakeGame:
    def __init__(self):
        self.game_id = "y8YKMP5FtG7rhzpv"
        self.order_history = {}
        self.state_history = {}
        self.phase = "SPRING 1901 MOVEMENT"
        self.is_game_done = False
        self.powers = ["AUSTRIA", "ENGLAND", "FRANCE", "GERMANY", "ITALY", "RUSSIA", "TURKEY"]

    def set_orders(self, *args):
        pass

    def process(self):
        pass

    def get_phase_history(self):
        return []

    def get_orderable_locations(self, power=None):
        d = {
            "AUSTRIA": ["BUD", "TRI", "VIE"],
            "ENGLAND": ["EDI", "LON", "LVP"],
            "FRANCE": ["BRE", "MAR", "PAR"],
            "GERMANY": ["BER", "KIE", "MUN"],
            "ITALY": ["NAP", "ROM", "VEN"],
            "RUSSIA": ["MOS", "SEV", "STP", "WAR"],
            "TURKEY": ["ANK", "CON", "SMY"],
        }
        if power is None:
            return d
        else:
            return d[power]

    def get_state(self):
        return {
            "timestamp": 1574350863290709,
            "zobrist_hash": "1919110489198082658",
            "note": "",
            "name": "S1901M",
            "units": {
                "AUSTRIA": ["A BUD", "A VIE", "F TRI"],
                "ENGLAND": ["F EDI", "F LON", "A LVP"],
                "FRANCE": ["F BRE", "A MAR", "A PAR"],
                "GERMANY": ["F KIE", "A BER", "A MUN"],
                "ITALY": ["F NAP", "A ROM", "A VEN"],
                "RUSSIA": ["A WAR", "A MOS", "F SEV", "F STP/SC"],
                "TURKEY": ["F ANK", "A CON", "A SMY"],
            },
            "retreats": {
                "AUSTRIA": {},
                "ENGLAND": {},
                "FRANCE": {},
                "GERMANY": {},
                "ITALY": {},
                "RUSSIA": {},
                "TURKEY": {},
            },
            "centers": {
                "AUSTRIA": ["BUD", "TRI", "VIE"],
                "ENGLAND": ["EDI", "LON", "LVP"],
                "FRANCE": ["BRE", "MAR", "PAR"],
                "GERMANY": ["BER", "KIE", "MUN"],
                "ITALY": ["NAP", "ROM", "VEN"],
                "RUSSIA": ["MOS", "SEV", "STP", "WAR"],
                "TURKEY": ["ANK", "CON", "SMY"],
            },
            "homes": {
                "AUSTRIA": ["BUD", "TRI", "VIE"],
                "ENGLAND": ["EDI", "LON", "LVP"],
                "FRANCE": ["BRE", "MAR", "PAR"],
                "GERMANY": ["BER", "KIE", "MUN"],
                "ITALY": ["NAP", "ROM", "VEN"],
                "RUSSIA": ["MOS", "SEV", "STP", "WAR"],
                "TURKEY": ["ANK", "CON", "SMY"],
            },
            "influence": {
                "AUSTRIA": ["BUD", "VIE", "TRI"],
                "ENGLAND": ["EDI", "LON", "LVP"],
                "FRANCE": ["BRE", "MAR", "PAR"],
                "GERMANY": ["KIE", "BER", "MUN"],
                "ITALY": ["NAP", "ROM", "VEN"],
                "RUSSIA": ["WAR", "MOS", "SEV", "STP"],
                "TURKEY": ["ANK", "CON", "SMY"],
            },
            "civil_disorder": {
                "AUSTRIA": 0,
                "ENGLAND": 0,
                "FRANCE": 0,
                "GERMANY": 0,
                "ITALY": 0,
                "RUSSIA": 0,
                "TURKEY": 0,
            },
            "builds": {
                "AUSTRIA": {"count": 0, "homes": []},
                "ENGLAND": {"count": 0, "homes": []},
                "FRANCE": {"count": 0, "homes": []},
                "GERMANY": {"count": 0, "homes": []},
                "ITALY": {"count": 0, "homes": []},
                "RUSSIA": {"count": 0, "homes": []},
                "TURKEY": {"count": 0, "homes": []},
            },
        }

    def get_all_possible_orders(self):
        return {
            "ADR": [],
            "AEG": [],
            "ALB": [],
            "ANK": [
                "F ANK S F SEV - ARM",
                "F ANK - CON",
                "F ANK - ARM",
                "F ANK S A SMY - ARM",
                "F ANK - BLA",
                "F ANK S A CON",
                "F ANK H",
                "F ANK S A SMY - CON",
                "F ANK S F SEV - BLA",
            ],
            "APU": [],
            "ARM": [],
            "BAL": [],
            "BAR": [],
            "BEL": [],
            "BER": [
                "A BER S A MUN - KIE",
                "A BER H",
                "A BER S A WAR - PRU",
                "A BER S A WAR - SIL",
                "A BER S F KIE",
                "A BER - MUN",
                "A BER - KIE",
                "A BER - PRU",
                "A BER - SIL",
                "A BER S A MUN",
                "A BER S A MUN - SIL",
            ],
            "BLA": [],
            "BOH": [],
            "BOT": [],
            "BRE": [
                "F BRE - GAS",
                "F BRE S F LON - ENG",
                "F BRE S A PAR - GAS",
                "F BRE - ENG",
                "F BRE S A PAR - PIC",
                "F BRE - PIC",
                "F BRE S A MAR - GAS",
                "F BRE - MAO",
                "F BRE H",
            ],
            "BUD": [
                "A BUD H",
                "A BUD S A VEN - TRI",
                "A BUD - GAL",
                "A BUD S F SEV - RUM",
                "A BUD - SER",
                "A BUD S A WAR - GAL",
                "A BUD S A VIE - TRI",
                "A BUD - RUM",
                "A BUD S F TRI",
                "A BUD - TRI",
                "A BUD S A VIE",
                "A BUD - VIE",
                "A BUD S A VIE - GAL",
            ],
            "BUL/EC": [],
            "BUL/SC": [],
            "BUL": [],
            "BUR": [],
            "CLY": [],
            "CON": [
                "A CON H",
                "A CON - ANK",
                "A CON S F ANK",
                "A CON - SMY",
                "A CON - BUL",
                "A CON S A SMY - ANK",
                "A CON S A SMY",
            ],
            "DEN": [],
            "EAS": [],
            "EDI": [
                "F EDI - NTH",
                "F EDI - NWG",
                "F EDI S A LVP - YOR",
                "F EDI S F LON - YOR",
                "F EDI S A LVP - CLY",
                "F EDI - YOR",
                "F EDI S F LON - NTH",
                "F EDI - CLY",
                "F EDI H",
            ],
            "ENG": [],
            "FIN": [],
            "GAL": [],
            "GAS": [],
            "GRE": [],
            "HEL": [],
            "HOL": [],
            "ION": [],
            "IRI": [],
            "KIE": [
                "F KIE - DEN",
                "F KIE - HEL",
                "F KIE S A MUN - BER",
                "F KIE S A BER",
                "F KIE H",
                "F KIE - BAL",
                "F KIE - BER",
                "F KIE - HOL",
            ],
            "LON": [
                "F LON - ENG",
                "F LON - NTH",
                "F LON - WAL",
                "F LON - YOR",
                "F LON S F BRE - ENG",
                "F LON H",
                "F LON S A LVP - YOR",
                "F LON S F EDI - YOR",
                "F LON S F EDI - NTH",
                "F LON S A LVP - WAL",
            ],
            "LVN": [],
            "LVP": [
                "A LVP S F EDI - CLY",
                "A LVP - CLY",
                "A LVP S F EDI",
                "A LVP H",
                "A LVP - WAL",
                "A LVP S F LON - YOR",
                "A LVP - YOR",
                "A LVP S F EDI - YOR",
                "A LVP - EDI",
                "A LVP S F LON - WAL",
            ],
            "LYO": [],
            "MAO": [],
            "MAR": [
                "A MAR - BUR",
                "A MAR H",
                "A MAR S A PAR - GAS",
                "A MAR S A VEN - PIE",
                "A MAR - GAS",
                "A MAR - PIE",
                "A MAR S A MUN - BUR",
                "A MAR - SPA",
                "A MAR S F BRE - GAS",
                "A MAR S A PAR - BUR",
            ],
            "MOS": [
                "A MOS S F STP/SC",
                "A MOS - UKR",
                "A MOS H",
                "A MOS - LVN",
                "A MOS S A WAR - UKR",
                "A MOS S A WAR - LVN",
                "A MOS - SEV",
                "A MOS - WAR",
                "A MOS - STP",
                "A MOS S A WAR",
                "A MOS S F STP/SC - LVN",
                "A MOS S F SEV",
            ],
            "MUN": [
                "A MUN S A VIE - BOH",
                "A MUN - BUR",
                "A MUN - TYR",
                "A MUN S A BER - SIL",
                "A MUN - RUH",
                "A MUN S A PAR - BUR",
                "A MUN S F KIE",
                "A MUN S A WAR - SIL",
                "A MUN S A VEN - TYR",
                "A MUN S A MAR - BUR",
                "A MUN - BOH",
                "A MUN S A BER - KIE",
                "A MUN - SIL",
                "A MUN H",
                "A MUN S F KIE - BER",
                "A MUN - KIE",
                "A MUN - BER",
                "A MUN S A VIE - TYR",
                "A MUN S A BER",
            ],
            "NAF": [],
            "NAO": [],
            "NAP": [
                "F NAP H",
                "F NAP S A ROM",
                "F NAP - APU",
                "F NAP - ROM",
                "F NAP - ION",
                "F NAP S A ROM - APU",
                "F NAP - TYS",
                "F NAP S A VEN - APU",
                "F NAP S A VEN - ROM",
            ],
            "NWY": [],
            "NTH": [],
            "NWG": [],
            "PAR": [
                "A PAR - GAS",
                "A PAR S F BRE - GAS",
                "A PAR S F BRE",
                "A PAR - BRE",
                "A PAR - BUR",
                "A PAR H",
                "A PAR S A MUN - BUR",
                "A PAR S A MAR - GAS",
                "A PAR S F BRE - PIC",
                "A PAR - PIC",
                "A PAR S A MAR - BUR",
            ],
            "PIC": [],
            "PIE": [],
            "POR": [],
            "PRU": [],
            "ROM": [
                "A ROM S A VEN - TUS",
                "A ROM - NAP",
                "A ROM S F NAP",
                "A ROM S A VEN - APU",
                "A ROM S A VEN",
                "A ROM H",
                "A ROM S F NAP - APU",
                "A ROM - APU",
                "A ROM - VEN",
                "A ROM S F TRI - VEN",
                "A ROM - TUS",
            ],
            "RUH": [],
            "RUM": [],
            "SER": [],
            "SEV": [
                "F SEV S A BUD - RUM",
                "F SEV S A SMY - ARM",
                "F SEV S F ANK - ARM",
                "F SEV - ARM",
                "F SEV H",
                "F SEV - RUM",
                "F SEV - BLA",
                "F SEV S F ANK - BLA",
            ],
            "SIL": [],
            "SKA": [],
            "SMY": [
                "A SMY - SYR",
                "A SMY S F ANK - CON",
                "A SMY - ARM",
                "A SMY S F SEV - ARM",
                "A SMY S F ANK - ARM",
                "A SMY - ANK",
                "A SMY S A CON",
                "A SMY H",
                "A SMY S A CON - ANK",
                "A SMY - CON",
                "A SMY S F ANK",
            ],
            "SPA/NC": [],
            "SPA/SC": [],
            "SPA": [],
            "STP/NC": [],
            "STP/SC": [
                "F STP/SC - LVN",
                "F STP/SC - BOT",
                "F STP/SC H",
                "F STP/SC S A MOS - LVN",
                "F STP/SC - FIN",
                "F STP/SC S A WAR - LVN",
            ],
            "STP": [
                "F STP/SC - LVN",
                "F STP/SC - BOT",
                "F STP/SC H",
                "F STP/SC S A MOS - LVN",
                "F STP/SC - FIN",
                "F STP/SC S A WAR - LVN",
            ],
            "SWE": [],
            "SYR": [],
            "TRI": [
                "F TRI S A VEN",
                "F TRI S A ROM - VEN",
                "F TRI - ADR",
                "F TRI H",
                "F TRI - VEN",
                "F TRI - ALB",
            ],
            "TUN": [],
            "TUS": [],
            "TYR": [],
            "TYS": [],
            "UKR": [],
            "VEN": [
                "A VEN S A ROM",
                "A VEN - TYR",
                "A VEN S F TRI",
                "A VEN H",
                "A VEN S A BUD - TRI",
                "A VEN - TRI",
                "A VEN - PIE",
                "A VEN S F NAP - APU",
                "A VEN - APU",
                "A VEN S A MAR - PIE",
                "A VEN S A ROM - TUS",
                "A VEN S A VIE - TYR",
                "A VEN - TUS",
                "A VEN S A ROM - APU",
                "A VEN S A MUN - TYR",
                "A VEN S F NAP - ROM",
                "A VEN S A VIE - TRI",
                "A VEN - ROM",
            ],
            "VIE": [
                "A VIE S A VEN - TRI",
                "A VIE - TYR",
                "A VIE S F TRI",
                "A VIE S A BUD - GAL",
                "A VIE S A WAR - GAL",
                "A VIE - BOH",
                "A VIE S A MUN - TYR",
                "A VIE S A VEN - TYR",
                "A VIE - TRI",
                "A VIE S A BUD - TRI",
                "A VIE S A MUN - BOH",
                "A VIE S A BUD",
                "A VIE H",
                "A VIE - BUD",
                "A VIE - GAL",
            ],
            "WAL": [],
            "WAR": [
                "A WAR S F STP/SC - LVN",
                "A WAR H",
                "A WAR - UKR",
                "A WAR S A VIE - GAL",
                "A WAR S A MOS - LVN",
                "A WAR S A MUN - SIL",
                "A WAR - PRU",
                "A WAR S A BER - PRU",
                "A WAR S A BUD - GAL",
                "A WAR - GAL",
                "A WAR - LVN",
                "A WAR - MOS",
                "A WAR S A BER - SIL",
                "A WAR S A MOS - UKR",
                "A WAR S A MOS",
                "A WAR - SIL",
            ],
            "WES": [],
            "YOR": [],
            "SWI": [],
        }
