repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
-   repo: local
    hooks:
    -   id: clang-format
        name: clang-format
        description: Format proto files with clang-format
        entry: clang-format-8 -i
        language: system
        files: ^conf/.*\.(proto)$
exclude: '^(thirdpary|src)/'
